# Generated by Django 5.0.6 on 2024-06-28 01:39

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_comments_email_remove_comments_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='user',
        ),
        migrations.AddField(
            model_name='comments',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name=django.contrib.auth.models.User),
        ),
    ]
